---
title: "Leslie Matrix Practice"
author: "Henry Oliver"
format: html
---
```{r}
# Made a sequence of values from 1 to 10
my_vals <- seq(from = 1, to = 10, by = 1)

# Look at it (always)
my_vals

# Convert to matrix 
my_matrix <- matrix(data = my_vals, 
                    nrow = 2, 
                    ncol = 5, 
                    byrow = TRUE)

# Check it out
my_matrix

```
```{r}
4*my_matrix

#New values, some steps are skipped because of default stuff
my_vals_2 = seq(from = 21, to = 30)
my_matrix_2 = matrix(my_vals_2, nrow = 2, byrow = TRUE)
my_matrix_2

my_matrix+my_matrix_2
```

```{r}

# make a couple of 2x2 matrices
sheep <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow = TRUE)
lions <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)

sheep
lions

# Matrix multiplication
sheep%*%lions
```


```{r}
# Create your Leslie matrix
insect_leslie <- matrix(c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), 
                        nrow = 3,
                        ncol = 3, 
                        byrow = TRUE)

insect_leslie
```

Now specify initial conditions
```{r}
# insect lifestage population size (year 0)
insect_y0 <- c(1200, 700, 500)
```

Find the population for each lifestage at y1

```{r}
# Populations at year 1
insect_y1 <- insect_leslie %*% insect_y0

insect_y1

# Populations at year 2
insect_y2 <- insect_leslie %*% insect_y1

# Check it out
insect_y2
```
